user_pool:
  name: cf_user_pool

user_pool_client:
  name: cf_user_pool_client
  generate_secret: true
  call_back_urls:
    - Fn::Sub: https://app.${EnvironmentName}.${DnsDomain}/oauth2/idpresponse
  default_redirect_uri: 
    Fn::Sub: https://app.${EnvironmentName}.${DnsDomain}/oauth2/idpresponse
  allowed_oauth_flows_userpool_client: true
  allowed_oauth_flows:
    - code
  allowed_ouath_scopes:
    - phone
    - email
    - openid
    - profile
  explicit_auth_flows:
    - ALLOW_USER_PASSWORD_AUTH
    - ALLOW_REFRESH_TOKEN_AUTH
  supported_identity_providers:
    - COGNITO
  refresh_token_validity: 3650
  access_token_validity: 12
  
user_pool_domain:
  name: cf-domain