user_pool:
  name: cf_user_pool

user_pool_client:
  name: cf_user_pool_client
  generate_secret: true
  call_back_urls:
    - http://localhost:3000/
  default_redirect_uri: http://localhost:3000/
  allowed_oauth_flows_userpool_client: true
  allowed_oauth_flows:
    - code
    - implicit
  allowed_ouath_scopes:
    - openid
    - profile
  
user_pool_domain:
  name: cf-domain